import { Component, signal, computed, inject, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { WebLLMService } from './services/webllm.service';
import { DocumentAnalysisService } from './services/document-analysis.service';

/**
 * App Component - Main Application Shell
 *
 * Demonstrates modern Angular 19 patterns for AI-powered applications:
 *
 * Architecture Patterns:
 * - Standalone component (no NgModules) for better tree-shaking
 * - OnPush change detection for optimal performance
 * - Signal-based state management for fine-grained reactivity
 * - inject() function over constructor DI for cleaner code
 * - Computed signals for derived state
 *
 * AI Integration Strategy:
 * - Progressive enhancement: starts without AI, enables when ready
 * - Clear loading states with detailed progress tracking
 * - Graceful error handling and recovery
 * - Lazy initialization to avoid blocking app startup
 *
 * This is "AI-Assisted Engineering" in practice:
 * - Architecture designed by humans
 * - Boilerplate generated by AI
 * - Validated, tested, and refined for production
 */
@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './app.html'
})
export class App implements OnInit {
  protected readonly title = 'AI-Powered Angular Demos';

  readonly webllm = inject(WebLLMService);
  readonly docService = inject(DocumentAnalysisService);
  private readonly router = inject(Router);

  readonly showInitializer = computed(() => !this.webllm.isReady());

  ngOnInit() {
    // Auto-initialize with default model
    // You can change this to manual initialization if preferred
  }

  async initializeModel() {
    try {
      await this.webllm.initialize();
      // Navigate to document analyzer after successful initialization
      await this.router.navigate(['/document-analyzer']);
    } catch (error) {
      console.error('Failed to initialize model:', error);
    }
  }

  formatTime(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return mins > 0 ? `${mins}m ${secs}s` : `${secs}s`;
  }
}
